
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE ENJOY EQUALS ID LBRACE LPAREN MAIN MINUS NUMBER PLUS PRINT RBRACE RPAREN SEMICOLON STRING TIMESprogram : ENJOY MAIN LPAREN RPAREN LBRACE statements RBRACEstatements : statements statement\n                  | statementstatement : PRINT LPAREN STRING RPARENstatement : ID EQUALS expressionexpression : expression PLUS term\n                  | expression MINUS termexpression : termterm : term TIMES factor\n            | term DIVIDE factorterm : factorfactor : NUMBERfactor : ID'
    
_lr_action_items = {'ENJOY':([0,],[2,]),'$end':([1,11,],[0,-1,]),'MAIN':([2,],[3,]),'LPAREN':([3,9,],[4,13,]),'RPAREN':([4,15,],[5,21,]),'LBRACE':([5,],[6,]),'PRINT':([6,7,8,12,16,17,18,19,20,21,26,27,28,29,],[9,9,-3,-2,-13,-5,-8,-11,-12,-4,-6,-7,-9,-10,]),'ID':([6,7,8,12,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,],[10,10,-3,-2,16,-13,-5,-8,-11,-12,-4,16,16,16,16,-6,-7,-9,-10,]),'RBRACE':([7,8,12,16,17,18,19,20,21,26,27,28,29,],[11,-3,-2,-13,-5,-8,-11,-12,-4,-6,-7,-9,-10,]),'EQUALS':([10,],[14,]),'STRING':([13,],[15,]),'NUMBER':([14,22,23,24,25,],[20,20,20,20,20,]),'TIMES':([16,18,19,20,26,27,28,29,],[-13,24,-11,-12,24,24,-9,-10,]),'DIVIDE':([16,18,19,20,26,27,28,29,],[-13,25,-11,-12,25,25,-9,-10,]),'PLUS':([16,17,18,19,20,26,27,28,29,],[-13,22,-8,-11,-12,-6,-7,-9,-10,]),'MINUS':([16,17,18,19,20,26,27,28,29,],[-13,23,-8,-11,-12,-6,-7,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([6,],[7,]),'statement':([6,7,],[8,12,]),'expression':([14,],[17,]),'term':([14,22,23,],[18,26,27,]),'factor':([14,22,23,24,25,],[19,19,19,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> ENJOY MAIN LPAREN RPAREN LBRACE statements RBRACE','program',7,'p_program','parser.cpython-312.py',5),
  ('statements -> statements statement','statements',2,'p_statements','parser.cpython-312.py',9),
  ('statements -> statement','statements',1,'p_statements','parser.cpython-312.py',10),
  ('statement -> PRINT LPAREN STRING RPAREN','statement',4,'p_statement_print','parser.cpython-312.py',17),
  ('statement -> ID EQUALS expression','statement',3,'p_statement_assign','parser.cpython-312.py',21),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','parser.cpython-312.py',25),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','parser.cpython-312.py',26),
  ('expression -> term','expression',1,'p_expression_term','parser.cpython-312.py',30),
  ('term -> term TIMES factor','term',3,'p_term_binop','parser.cpython-312.py',34),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','parser.cpython-312.py',35),
  ('term -> factor','term',1,'p_term_factor','parser.cpython-312.py',39),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.cpython-312.py',43),
  ('factor -> ID','factor',1,'p_factor_id','parser.cpython-312.py',47),
]
